### ISSUE TITLE
FC017: Notifications in private methods not followed

### ISSUE THREAD

**Issue by moserke** [Foodcritic/foodcritic#171]
Given the following code:

``` ruby
action :create
  create_something
end

private
def create_something
  new_resource.updated_by_last_action(true)
end
```

Assuming that create_something does something useful and then calls the notification, this no longer passes FC017.

Lines 219-232 in the rules.rb would need to recursively follow method calls to the end of the tree and see if the updated_by_last_action is called in there.  Maybe not worth it and force people to change their implementations or maybe so.

Example of this can be found in the windows_registry provider and is also where it now fails for us where it was passing before.

**Comment by tas50** [comment]
FC059 makes the need to fix this invalid. updated_by_last_action really shouldn't be used and we're going to have a rule for that in the near future. Chef 13 ships with use_inline_resources on by default so you need to use converge_by or just allow the resources to do their thing and update state.

**Comment by lamont-granquist** [comment]
Chef-14 will also most likely have use_inline_resources on by default even if you use `def action_whatever` instead of the helper `action :whatever` (which is what wires up use_inline_resources) which will make it much more difficult to write resources without use_inline_resources and will likely break any code that attempts to do old Chef-10 style resources+providers and uses updated_by_last_action directly.
