### ISSUE TITLE
Add a rule for using package with a specified provider

### ISSUE THREAD

**Issue by tas50** [Foodcritic/foodcritic#490]
@lamont-granquist noted in https://github.com/chef/chef/issues/5350 that doing so is not going to result in what the user wants / thinks is happening. We should alert on this.

**Comment by lamont-granquist** [comment]
yeah to be perfectly clear:

```
package "whatever" do
  provider Chef::Provider::Package::SomethingOrOther
end
```

that never worked well, and works worse in chef 12.

should be replaced by declare_resource:

```
declare_resource(:something_package) do
   ...
end
```

the latter does "eager" dynamic resolution and picks the correct resource class.  the former has to create a resource to pass the block into, and it creates a Chef::Resource::Package on Chef 11 (which was incorrect) and creates a Chef::Resource::YumPackage or Chef::Resource::AptPackage in Chef 12 (which gets the common use case *correct* in a way that Chef 11 did not, while making this use case worse).  in order to treat this as a 'bug' you'd have to warp space and time because the provider argument that you haven't yet parsed needs to be used to pick the correct resource class to feed the block into.

also raw ruby classes (the Chef::Provider::Package::SomethingOrOther in the first case) are always a sign of tight coupling and that replacing that with a symbol is looser coupling (:something_package).

**Comment by lamont-granquist** [comment]
note however that for the service resource switching the provider is still the recommended way of doing things -- that resource is still one resource class fascade over multiple provider implementations which are late-bound and is not a 1:1 resource-to-provider model.

**Comment by tas50** [comment]
Fixed by https://github.com/Foodcritic/foodcritic/pull/699
