### ISSUE TITLE
FC009 - chef_gem attribute include_default_source

### ISSUE THREAD

**Issue by cdbeard2016** [Foodcritic/foodcritic#628]
Hi!

It looks like a new include_default_source attribute was added to the chef_gem resource recently which is flagged not recognised by FC009.

```
chef_gem 'chef-vault' do
  include_default_source false
  action :install
  source 'some_source'
end
```

ChefDK: 1.3.43
Foodcritic: 11.0.0

Thanks,

Chris

**Comment by tas50** [comment]
You can set the metadata version to the latest in Chef 13 and this will go away. Right now Foodcritic 11.0 is set to default to 11.19 and 11.1 is defaulting to 12.20. It's a fine line to walk since Chef 13 removed a huge number of methods and switching to 13.0 would have broken a ton of people on FC009. I'll probably bump it up to 13.1 in the next Foodcritic release.
