### ISSUE TITLE
FC009 incorrectly flag `default_release`

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [Foodcritic/foodcritic#662]
### Info
foodcritic 11.3.0
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1

### Description
Foodcritic is complaining about the attribute `default_release` in `package` resource

Example:
```
package 'certbot' do
   default_release 'jessie-backports' unless node['platform_version'].to_i != 8
   action :install
end
```

**Comment by tas50** [comment]
The problem is Foodcritic doesn't know about the valid properties of the actual underlying package resources. In this case there's some magic that occurs and you're actually running apt_package, which includes default_release. Foodcritic doesn't know you're on a Debian like system and that Chef would actually run the apt_package resource where this is valid. This is where statically analyzing source code is hard and really falls over. The only release solution is to put a comment in your code to ignore that rule here.
