### ISSUE TITLE
Dash docset cannot be installed

### ISSUE THREAD

**Issue by jeffbyrnes** [Foodcritic/foodcritic#663]
Either by clicking the link on foodcritic.io, or by clicking “Download” inside Dash’s “Downloads” preferences, I get a 403 error.

I’m able to visit the link in question directly, in a browser, without any trouble.

**Comment by tescalada** [comment]
http://www.foodcritic.io/dash/Foodcritic.tgz returns an access denied error to me.

**Comment by jeffbyrnes** [comment]
I too, now get a 403 error when I visit that link. Trying using HTTPS fails b/c “cannot establish a secure connection”.

**Comment by juliandunn** [comment]
I looked into this briefly and it is a problem with the Rake tasks over in https://github.com/Foodcritic/foodcritic-site rather than this repo. (A `403` on an S3-backed website doesn't mean access denied; it often means the resource doesn't exist.) However, those tasks don't seem to work; I managed to get a `Foodcritic.tgz` Dash docset on disk after some fiddling, but `middleman s3_sync` doesn't seem to want to sync it to S3.

Not to mention that the Travis job at present doesn't even invoke the deploy rake task so idk how the site is even getting published...

**Comment by tas50** [comment]
The deploy happens via Rake manually. I'll take a look at the job for syncing the tarball tomorrow.

**Comment by jeffbyrnes** [comment]
Thanks @tas50!

**Comment by tas50** [comment]
There was a missing step in the Rakefile that generates the docset. It still needs improved logic to create the right version number, but it's not a 404 anymore at least.

https://github.com/Foodcritic/foodcritic-site/commit/181aac36b9a3ccdb58cb42f2e37e69cac3ac17fe

**Comment by jeffbyrnes** [comment]
I can confirm that now, at least, I can install docset. Thanks very much!
